package:
  name: d3d
  version: {{ VERSION }}

source:
  path: ../..
  # git_url: https://github.com/cmpute/d3d.git
  # git_rev: v{{ VERSION }}

build:
  number: 0
  string: "py{{ py }}_{{ PKG_BUILDNUM }}_torch{{ pytorch }}_cpu"
  skip: True  # [win]
  script:
    - export CMAKE_GENERATOR=Ninja # [unix]
    - export USE_CUDA=0 # [unix]
    - set USE_CUDA=0 # [win] 
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make  # [unix]
  host:
    - python {{ python }}
    - setuptools
    - setuptools-scm
    - pytorch {{ pytorch }}
    - cpuonly
    - scikit-build
    - cython
  run:
    - python
    - pytorch
    - cpuonly
    - scipy
    - addict
    - pillow
    - tqdm
    - msgpack-python
    - filterpy

test:
  imports:
    - d3d

about:
  home: https://github.com/cmpute/d3d
  summary: Devkit for 3D object detection and tracking
  dev_url: https://github.com/cmpute/d3d

extra:
  recipe-maintainers:
    - cmpute