c_compiler:
- gcc
c_compiler_version:
- '7'
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cuda_compiler:
- nvcc
cuda_compiler_version:
- '9.2'
cxx_compiler:
- gxx
cxx_compiler_version:
- '7'
# docker_image:
# - condaforge/linux-anvil-cuda:9.2
# pin_run_as_build:
#   python:
#     min_pin: x.x
#     max_pin: x.x
python:
- 3.7.* *_cpython
# zip_keys:
# - - cuda_compiler_version
#   - docker_image
