c_compiler_version:
- '7'
cxx_compiler_version:
- '7'
cuda_compiler:
- nvcc
cuda_compiler_version:
# - '9.2'
- '10.1'
python:
- '3.6'
pytorch:
- '1.4.0'
- '1.5.0'
- '1.5.1'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  pytorch:
    min_pin: x.x.x
    max_pin: x.x.x
