{% set version = "0.0.4c" %}

package:
  name: d3d
  version: {{ version }}

source:
  # path: ..
  git_url: https://github.com/cmpute/d3d.git
  git_rev: v{{ version }}

build:
  number: 0
  skip: True  # [win]
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    - cmake
  host:
    - setuptools
    - setuptools-scm
    - python {{ python }}
    - pytorch {{ pytorch }}
    - cudatoolkit-dev
    - cudnn
    - scikit-build
    - cython
  run:
    - python
    - pytorch
    - cudatoolkit
    - scipy

about:
  home: https://github.com/cmpute/d3d
  summary: Devkit for 3D object detection and tracking
  dev_url: https://github.com/cmpute/d3d

extra:
  recipe-maintainers:
    - cmpute