{% set version = "0.0.4b" %}

package:
  name: d3d
  version: {{ version }}

source:
  path: ..
  # url: https://github.com/cmpute/d3d/archive/v{{ version }}.tar.gz

build:
  number: 0
  skip: True  # [win]
  script:
    - python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
  host:
    - cmake
    - setuptools
    - python {{ python }}
    - pytorch
    - cudatoolkit-dev
    - cudnn
    - scikit-build
    - cython
  run:
    - python {{ python }}
    - pytorch
    - cudatoolkit
    - scipy

about:
  home: https://github.com/cmpute/d3d
  # license: BSD
  summary: Devkit for 3D object detection and tracking
  dev_url: https://github.com/cmpute/d3d

extra:
  recipe-maintainers:
    - cmpute